### ISSUE TITLE
create-vue-kotlin-app

### ISSUE THREAD

**Issue by sinadarvi** [nosix/vue-kotlin#3]
Your work is awesome. Wouldn't be wonderful to have create-vue-kotlin-app command? 
I know you probably have though to do that but i'm realy look into this that I woundering will you plannaning to do that or not.

**Comment by nosix** [comment]
Thanks.

I started this project with the aim of learning vue.js and Kotlin/JS. Therefore, there are many things I do not know about vue.js. Currently, there is no plan to continue this project. You can fork and use it in whole or in part.
